import Articulated from "Objects/articulated";
import Node from "Objects/node";
import generateDefaultArrayOfFace from "Main/default-array-of-face";

function generateDefaultArticulated(): Articulated {
  return new Articulated(
    new Node(
      "point-between-feet",
      [
        new Node(
          "waist",
          [
            new Node(
              "torso",
              [
                new Node(
                  "neck",
                  [
                    new Node(
                      "head",
                      [],
                      generateDefaultArrayOfFace(),
                      0,
                      -50,
                      0,
                      0,
                      0,
                      0,
                      1,
                      1,
                      1
                    ),
                  ],
                  generateDefaultArrayOfFace(),
                  0,
                  -50,
                  0,
                  0,
                  0,
                  0,
                  1,
                  1,
                  1
                ),
                new Node(
                  "left-arm",
                  [
                    new Node(
                      "left-forearm",
                      [
                        new Node(
                          "left-hand",
                          [],
                          generateDefaultArrayOfFace(),
                          -50,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          1,
                          1
                        ),
                      ],
                      generateDefaultArrayOfFace(),
                      -50,
                      0,
                      0,
                      0,
                      0,
                      0,
                      1,
                      1,
                      1
                    ),
                  ],
                  generateDefaultArrayOfFace(),
                  -50,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  1,
                  1
                ),
                new Node(
                  "right-arm",
                  [
                    new Node(
                      "right-forearm",
                      [
                        new Node(
                          "right-hand",
                          [],
                          generateDefaultArrayOfFace(),
                          50,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          1,
                          1
                        ),
                      ],
                      generateDefaultArrayOfFace(),
                      50,
                      0,
                      0,
                      0,
                      0,
                      0,
                      1,
                      1,
                      1
                    ),
                  ],
                  generateDefaultArrayOfFace(),
                  50,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  1,
                  1
                ),
              ],
              generateDefaultArrayOfFace(),
              0,
              -100,
              0,
              0,
              0,
              0,
              1,
              1,
              1
            ),
            new Node(
              "left-leg",
              [
                new Node(
                  "left-calf",
                  [
                    new Node(
                      "left-foot",
                      [],
                      generateDefaultArrayOfFace(),
                      0,
                      50,
                      0,
                      0,
                      0,
                      0,
                      1,
                      1,
                      1
                    ),
                  ],
                  generateDefaultArrayOfFace(),
                  0,
                  50,
                  0,
                  0,
                  0,
                  0,
                  1,
                  1,
                  1
                ),
              ],
              generateDefaultArrayOfFace(),
              -50,
              50,
              0,
              0,
              0,
              0,
              1,
              1,
              1
            ),
            new Node(
              "righty-leg",
              [
                new Node(
                  "right-calf",
                  [
                    new Node(
                      "right-foot",
                      [],
                      generateDefaultArrayOfFace(),
                      0,
                      50,
                      0,
                      0,
                      0,
                      0,
                      1,
                      1,
                      1
                    ),
                  ],
                  generateDefaultArrayOfFace(),
                  0,
                  50,
                  0,
                  0,
                  0,
                  0,
                  1,
                  1,
                  1
                ),
              ],
              generateDefaultArrayOfFace(),
              50,
              50,
              0,
              0,
              0,
              0,
              1,
              1,
              1
            ),
          ],
          generateDefaultArrayOfFace(),
          0,
          -150,
          0,
          0,
          0,
          0,
          1,
          1,
          1
        ),
      ],
      [],
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1
    )
  );
}

export default generateDefaultArticulated;
